import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faHeart,
    faShoppingCart,
    faSearch,
    faUser,
    faFrown,
    faRandom,
    faPlus,
    faMinus,
    faEnvelope,
    faAngleLeft,
    faAngleRight,
    faLongArrowAltUp,
    faArrowUp,
    faCircleExclamation,
    faFire,
    faTag,
    faBolt,
    faStar,
    faEye,
    faExpand,
    faPlay,
} from '@fortawesome/free-solid-svg-icons';

import { faFacebookF, faInstagram, faYoutube, faTwitter, faGooglePlusG, faPinterest } from '@fortawesome/free-brands-svg-icons';

library.add(
    faHeart,
    faShoppingCart,
    faSearch,
    faUser,
    faFrown,
    faRandom,
    faPlus,
    faMinus,
    faEnvelope,
    faAngleLeft,
    faAngleRight,
    faLongArrowAltUp,
    faArrowUp,
    faCircleExclamation,
    faFacebookF,
    faInstagram,
    faYoutube,
    faTwitter,
    faGooglePlusG,
    faPinterest,
    faFire,
    faTag,
    faBolt,
    faStar,
    faEye,
    faExpand,
    faPlay
);
